<?php
// module/Album/view/album/album/delete.phtml:

$title = 'Delete Customer';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to delete
    '<?php echo $this->escapeHtml($project->id); ?>' by
    '<?php echo $this->escapeHtml($project->project_name); ?>'?
</p>
<?php
$url = $this->url('project', array(
    'action' => 'delete',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
    <div>
        <input type="hidden" name="id" value="<?php echo (int) $project->id; ?>" />
        <input type="submit" name="del" value="Yes" />
        <input type="submit" name="del" value="No" />
    </div>
</form>