<?php
// module/Album/view/album/album/add.phtml:

$title = 'Add new Project';
$this->headTitle($title);
?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('project', array('action' => 'add')));
$form->prepare();

// view ra từng phần tử của form như symfony
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('customer_id'));
echo $this->formRow($form->get('project_name'));
echo $this->formRow($form->get('project_descriptions'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();