<?php
// module/Album/view/album/album/add.phtml:

$title = 'Add new album';
$this->headTitle($title);
?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('customer', array('action' => 'add')));
$form->prepare();

// view ra từng phần tử của form như symfony
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('customer_name'));
echo $this->formRow($form->get('address'));
echo $this->formRow($form->get('customer_phone'));
echo $this->formRow($form->get('company_name'));
echo $this->formRow($form->get('tax_id'));
echo $this->formRow($form->get('company_phone'));
echo $this->formRow($form->get('company_fax'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();