<!DOCTYPE html>
<!--[if IE 8]>
<html lang="en" class="ie8">
</html>
<![endif]-->
<!--[if IE 9]>
<html lang="en" class="ie9">
</html>
<![endif]-->
<!--[if !IE]>
<!-->
<html lang="en">
  <!--
<![endif]-->
  <head>
    <meta charset="utf-8" />
    <title>
      Admin Lab Dashboard
    </title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />
    <meta content="" name="description" />
    <meta content="" name="author" />
    <link href="<?php echo $this->basePath(); ?>/templates/admin-main/assets/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="<?php echo $this->basePath(); ?>/templates/admin-main/assets/bootstrap/css/bootstrap-responsive.min.css" rel="stylesheet" />
    <link href="<?php echo $this->basePath(); ?>/templates/admin-main/assets/font-awesome/css/font-awesome.css" rel="stylesheet" />
    <link href="<?php echo $this->basePath(); ?>/templates/admin-main/css/style.min.css" rel="stylesheet" />
    <link href="<?php echo $this->basePath(); ?>/templates/admin-main/css/style_responsive.css" rel="stylesheet" />
    <link href="<?php echo $this->basePath(); ?>/templates/admin-main/css/style_default.css" rel="stylesheet" id="style_color" />
    <link href="<?php echo $this->basePath(); ?>/templates/admin-main/assets/fancybox/source/jquery.fancybox.css" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="<?php echo $this->basePath(); ?>/templates/admin-main/assets/uniform/css/uniform.default.css" />
    <link href="<?php echo $this->basePath(); ?>/templates/admin-main//assets/fullcalendar/fullcalendar/bootstrap-fullcalendar.css" rel="stylesheet" />
    <link href="<?php echo $this->basePath(); ?>/templates/admin-main/assets/jqvmap/jqvmap/jqvmap.css" media="screen" rel="stylesheet" type="text/css" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  </head>
  <body class="fixed-top">
    <div id="header" class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="brand" href="<?php echo $this->basePath(); ?>/templates/admin-main/index.html">
            <img src="<?php echo $this->basePath(); ?>/templates/admin-main/img/logo.png" alt="Admin Lab" />
          </a>
          <a class="btn btn-navbar collapsed" id="main_menu_trigger" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar">
            </span>
            <span class="icon-bar">
            </span>
            <span class="icon-bar">
            </span>
            <span class="arrow">
            </span>
          </a>
          <div id="top_menu" class="nav notify-row">
            <ul class="nav top-menu">
              <li class="dropdown">
                <a class="dropdown-toggle element" data-placement="bottom" data-toggle="tooltip" href="#" data-original-title="Settings">
                  <i class="icon-cog">
                  </i>
                </a>
              </li>
              <li class="dropdown" id="header_inbox_bar">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <i class="icon-envelope-alt">
                  </i>
                  <span class="badge badge-important">
                    5
                  </span>
                </a>
                <ul class="dropdown-menu extended inbox">
                  <li>
                    <p>
                      You have 5 new messages
                    </p>
                  </li>
                  <li>
                    <a href="#">
                      <span class="photo">
                        <img src="<?php echo $this->basePath(); ?>/templates/admin-main/img/avatar-mini.png" alt="avatar" />
                      </span>
                      <span class="subject">
                        <span class="from">
                          Dulal Khan
                        </span>
                        <span class="time">
                          Just now
                        </span>
                      </span>
                      <span class="message">
                        Hello, this is an example messages please check
                      </span>
                    </a>
                  </li>
                  <li>
                    <a href="#">
                      <span class="photo">
                        <img src="<?php echo $this->basePath(); ?>/templates/admin-main/img/avatar-mini.png" alt="avatar" />
                      </span>
                      <span class="subject">
                        <span class="from">
                          Rafiqul Islam
                        </span>
                        <span class="time">
                          10 mins
                        </span>
                      </span>
                      <span class="message">
                        Hi, Mosaddek Bhai how are you ?
                      </span>
                    </a>
                  </li>
                  <li>
                    <a href="#">
                      <span class="photo">
                        <img src="<?php echo $this->basePath(); ?>/templates/admin-main/img/avatar-mini.png" alt="avatar" />
                      </span>
                      <span class="subject">
                        <span class="from">
                          Sumon Ahmed
                        </span>
                        <span class="time">
                          3 hrs
                        </span>
                      </span>
                      <span class="message">
                        This is awesome dashboard templates
                      </span>
                    </a>
                  </li>
                  <li>
                    <a href="#">
                      <span class="photo">
                        <img src="<?php echo $this->basePath(); ?>/templates/admin-main/img/avatar-mini.png" alt="avatar" />
                      </span>
                      <span class="subject">
                        <span class="from">
                          Dulal Khan
                        </span>
                        <span class="time">
                          Just now
                        </span>
                      </span>
                      <span class="message">
                        Hello, this is an example messages please check
                      </span>
                    </a>
                  </li>
                  <li>
                    <a href="#">
                      See all messages
                    </a>
                  </li>
                </ul>
              </li>
              <li class="dropdown" id="header_notification_bar">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <i class="icon-bell-alt">
                  </i>
                  <span class="badge badge-warning">
                    7
                  </span>
                </a>
                <ul class="dropdown-menu extended notification">
                  <li>
                    <p>
                      You have 7 new notifications
                    </p>
                  </li>
                  <li>
                    <a href="#">
                      <span class="label label-important">
                        <i class="icon-bolt">
                        </i>
                      </span>
                      Server #3 overloaded.
                      <span class="small italic">
                        34 mins
                      </span>
                    </a>
                  </li>
                  <li>
                    <a href="#">
                      <span class="label label-warning">
                        <i class="icon-bell">
                        </i>
                      </span>
                      Server #10 not respoding.
                      <span class="small italic">
                        1 Hours
                      </span>
                    </a>
                  </li>
                  <li>
                    <a href="#">
                      <span class="label label-important">
                        <i class="icon-bolt">
                        </i>
                      </span>
                      Database overloaded 24%.
                      <span class="small italic">
                        4 hrs
                      </span>
                    </a>
                  </li>
                  <li>
                    <a href="#">
                      <span class="label label-success">
                        <i class="icon-plus">
                        </i>
                      </span>
                      New user registered.
                      <span class="small italic">
                        Just now
                      </span>
                    </a>
                  </li>
                  <li>
                    <a href="#">
                      <span class="label label-info">
                        <i class="icon-bullhorn">
                        </i>
                      </span>
                      Application error.
                      <span class="small italic">
                        10 mins
                      </span>
                    </a>
                  </li>
                  <li>
                    <a href="#">
                      See all notifications
                    </a>
                  </li>
                </ul>
              </li>
            </ul>
          </div>
          <div class="top-nav ">
            <ul class="nav pull-right top-menu">
              <li class="dropdown mtop5">
                <a class="dropdown-toggle element" data-placement="bottom" data-toggle="tooltip" href="#" data-original-title="Chat">
                  <i class="icon-comments-alt">
                  </i>
                </a>
              </li>
              <li class="dropdown mtop5">
                <a class="dropdown-toggle element" data-placement="bottom" data-toggle="tooltip" href="#" data-original-title="Help">
                  <i class="icon-headphones">
                  </i>
                </a>
              </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <img src="<?php echo $this->basePath(); ?>/templates/admin-main/img/avatar1_small.jpg" alt="" />
                  <span class="username">
                    Mosaddek Hossain
                  </span>
                  <b class="caret">
                  </b>
                </a>
                <ul class="dropdown-menu">
                  <li>
                    <a href="#">
                      <i class="icon-user">
                      </i>
                      My Profile
                    </a>
                  </li>
                  <li>
                    <a href="#">
                      <i class="icon-tasks">
                      </i>
                      My Tasks
                    </a>
                  </li>
                  <li>
                    <a href="#">
                      <i class="icon-calendar">
                      </i>
                      Calendar
                    </a>
                  </li>
                  <li class="divider">
                  </li>
                  <li>
                    <a href="<?php echo $this->basePath(); ?>/templates/admin-main/login.html">
                      <i class="icon-key">
                      </i>
                      Log Out
                    </a>
                  </li>
                </ul>
              </li>
            </ul>
          </div>
        </div>
          <!-- END CONTENT  -->
      </div>
    </div>
    <div id="container" class="row-fluid">
      <div id="sidebar" class="nav-collapse collapse">
        <div class="sidebar-toggler hidden-phone">
        </div>
        <div class="navbar-inverse">
          <form class="navbar-search visible-phone" />
          <input type="text" class="search-query" placeholder="Search" />
        </form>
      </div>
      <ul class="sidebar-menu">
        <li class="has-sub active">
          <a href="javascript:;" class="">
            <span class="icon-box">
              <i class="icon-dashboard">
              </i>
            </span>
            Dashboard
            <span class="arrow">
            </span>
          </a>
          <ul class="sub">
            <li class="active">
              <a class="" href="<?php echo $this->basePath(); ?>/templates/admin-main/index.html">
                Dashboard 1
              </a>
            </li>
            <li>
              <a class="" href="<?php echo $this->basePath(); ?>/templates/admin-main/index_2.html">
                Dashboard 2
              </a>
            </li>
          </ul>
        </li>
        <li class="has-sub">
          <a href="javascript:;" class="">
            <span class="icon-box">
              <i class="icon-book">
              </i>
            </span>
            UI Elements
            <span class="arrow">
            </span>
          </a>
          <ul class="sub">
            <li>
              <a class="" href="<?php echo $this->basePath(); ?>/templates/admin-main/ui_elements_general.html">
                General
              </a>
            </li>
            <li>
              <a class="" href="<?php echo $this->basePath(); ?>/templates/admin-main/ui_elements_buttons.html">
                Buttons
              </a>
            </li>
            <li>
              <a class="" href="<?php echo $this->basePath(); ?>/templates/admin-main/ui_elements_tabs_accordions.html">
                Tabs & Accordions
              </a>
            </li>
            <li>
              <a class="" href="<?php echo $this->basePath(); ?>/templates/admin-main/ui_elements_typography.html">
                Typography
              </a>
            </li>
          </ul>
        </li>
        <li class="has-sub">
          <a href="javascript:;" class="">
            <span class="icon-box">
              <i class="icon-cogs">
              </i>
            </span>
            Components
            <span class="arrow">
            </span>
          </a>
          <ul class="sub">
            <li>
              <a class="" href="<?php echo $this->basePath(); ?>/templates/admin-main/calendar.html">
                Calendar
              </a>
            </li>
            <li>
              <a class="" href="<?php echo $this->basePath(); ?>/templates/admin-main/data_table.html">
                Data Table
              </a>
            </li>
            <li>
              <a class="" href="<?php echo $this->basePath(); ?>/templates/admin-main/grids.html">
                Grids
              </a>
            </li>
            <li>
              <a class="" href="<?php echo $this->basePath(); ?>/templates/admin-main/charts.html">
                Visual Charts
              </a>
            </li>
            <li>
              <a class="" href="<?php echo $this->basePath(); ?>/templates/admin-main/messengers.html">
                Conversations
              </a>
            </li>
            <li>
              <a class="" href="<?php echo $this->basePath(); ?>/templates/admin-main/gallery.html">
                Gallery
              </a>
            </li>
          </ul>
        </li>
        <li class="has-sub">
          <a href="javascript:;" class="">
            <span class="icon-box">
              <i class="icon-tasks">
              </i>
            </span>
            Form Stuff
            <span class="arrow">
            </span>
          </a>
          <ul class="sub">
            <li>
              <a class="" href="<?php echo $this->basePath(); ?>/templates/admin-main/form_layout.html">
                Form Layouts
              </a>
            </li>
            <li>
              <a class="" href="<?php echo $this->basePath(); ?>/templates/admin-main/form_component.html">
                Form Components
              </a>
            </li>
            <li>
              <a class="" href="<?php echo $this->basePath(); ?>/templates/admin-main/form_wizard.html">
                Form Wizard
              </a>
            </li>
            <li>
              <a class="" href="<?php echo $this->basePath(); ?>/templates/admin-main/form_validation.html">
                Form Validation
              </a>
            </li>
          </ul>
        </li>
        <li class="has-sub">
          <a href="javascript:;" class="">
            <span class="icon-box">
              <i class="icon-fire">
              </i>
            </span>
            Icons
            <span class="arrow">
            </span>
          </a>
          <ul class="sub">
            <li>
              <a class="" href="<?php echo $this->basePath(); ?>/templates/admin-main/font_awesome.html">
                Font Awesome
              </a>
            </li>
            <li>
              <a class="" href="<?php echo $this->basePath(); ?>/templates/admin-main/glyphicons.html">
                Glyphicons
              </a>
            </li>
          </ul>
        </li>
        <li class="has-sub">
          <a href="javascript:;" class="">
            <span class="icon-box">
              <i class="icon-map-marker">
              </i>
            </span>
            Maps
            <span class="arrow">
            </span>
          </a>
          <ul class="sub">
            <li>
              <a class="" href="<?php echo $this->basePath(); ?>/templates/admin-main/maps_google.html">
                Google Maps
              </a>
            </li>
            <li>
              <a class="" href="<?php echo $this->basePath(); ?>/templates/admin-main/maps_vector.html">
                Vector Maps
              </a>
            </li>
          </ul>
        </li>
        <li class="has-sub">
          <a href="javascript:;" class="">
            <span class="icon-box">
              <i class="icon-file-alt">
              </i>
            </span>
            Sample Pages
            <span class="arrow">
            </span>
          </a>
          <ul class="sub">
            <li>
              <a class="" href="<?php echo $this->basePath(); ?>/templates/admin-main/profile.html">
                Profile
              </a>
            </li>
            <li>
              <a class="" href="<?php echo $this->basePath(); ?>/templates/admin-main/blank.html">
                Blank Page
              </a>
            </li>
            <li>
              <a class="" href="<?php echo $this->basePath(); ?>/templates/admin-main/sidebar_closed.html">
                Sidebar Closed Page
              </a>
            </li>
            <li>
              <a class="" href="<?php echo $this->basePath(); ?>/templates/admin-main/pricing_tables.html">
                Pricing Tables
              </a>
            </li>
            <li>
              <a class="" href="<?php echo $this->basePath(); ?>/templates/admin-main/faq.html">
                FAQ
              </a>
            </li>
            <li>
              <a class="" href="<?php echo $this->basePath(); ?>/templates/admin-main/errors.html">
                Errors
              </a>
            </li>
          </ul>
        </li>
        <li>
          <a class="" href="<?php echo $this->basePath(); ?>/templates/admin-main/login.html">
            <span class="icon-box">
              <i class="icon-user">
              </i>
            </span>
            Login Page
          </a>
        </li>
      </ul>
    </div>
    <div id="main-content">
      <div class="container-fluid">
          <?php echo $this->layout()->content; ?>
      </div>
    </div>
</div>
<div id="footer">
  2013 &copy; Admin Lab Dashboard.
  <div class="span pull-right">
    <span class="go-top">
      <i class="icon-arrow-up">
      </i>
    </span>
  </div>
</div>
<script src="<?php echo $this->basePath(); ?>/templates/admin-main/js/jquery-1.8.3.min.js">
</script>
<script src="<?php echo $this->basePath(); ?>/templates/admin-main/assets/jquery-slimscroll/jquery-ui-1.9.2.custom.min.js">
</script>
<script src="<?php echo $this->basePath(); ?>/templates/admin-main/assets/jquery-slimscroll/jquery.slimscroll.min.js">
</script>
<script src="<?php echo $this->basePath(); ?>/templates/admin-main/assets/fullcalendar/fullcalendar/fullcalendar.min.js">
</script>
<script src="<?php echo $this->basePath(); ?>/templates/admin-main/assets/bootstrap/js/bootstrap.min.js">
</script>
<script src="<?php echo $this->basePath(); ?>/templates/admin-main/js/jquery.blockui.js">
</script>
<script src="<?php echo $this->basePath(); ?>/templates/admin-main/js/jquery.cookie.js">
</script>
<!--[if lt IE 9]>
<script src="<?php echo $this->basePath(); ?>/templates/admin-main/js/excanvas.js">
</script>
<script src="<?php echo $this->basePath(); ?>/templates/admin-main/js/respond.js">
</script>
<![endif]-->
<script src="<?php echo $this->basePath(); ?>/templates/admin-main/assets/jqvmap/jqvmap/jquery.vmap.js" type="text/javascript">
</script>
<script src="<?php echo $this->basePath(); ?>/templates/admin-main/assets/jqvmap/jqvmap/maps/jquery.vmap.russia.js" type="text/javascript">
</script>
<script src="<?php echo $this->basePath(); ?>/templates/admin-main/assets/jqvmap/jqvmap/maps/jquery.vmap.world.js" type="text/javascript">
</script>
<script src="<?php echo $this->basePath(); ?>/templates/admin-main/assets/jqvmap/jqvmap/maps/jquery.vmap.europe.js" type="text/javascript">
</script>
<script src="<?php echo $this->basePath(); ?>/templates/admin-main/assets/jqvmap/jqvmap/maps/jquery.vmap.germany.js" type="text/javascript">
</script>
<script src="<?php echo $this->basePath(); ?>/templates/admin-main/assets/jqvmap/jqvmap/maps/jquery.vmap.usa.js" type="text/javascript">
</script>
<script src="<?php echo $this->basePath(); ?>/templates/admin-main/assets/jqvmap/jqvmap/data/jquery.vmap.sampledata.js" type="text/javascript">
</script>
<script src="<?php echo $this->basePath(); ?>/templates/admin-main/assets/jquery-knob/js/jquery.knob.js">
</script>
<script src="<?php echo $this->basePath(); ?>/templates/admin-main/assets/flot/jquery.flot.js">
</script>
<script src="<?php echo $this->basePath(); ?>/templates/admin-main/assets/flot/jquery.flot.resize.js">
</script>
<script src="<?php echo $this->basePath(); ?>/templates/admin-main/assets/flot/jquery.flot.pie.js">
</script>
<script src="<?php echo $this->basePath(); ?>/templates/admin-main/assets/flot/jquery.flot.stack.js">
</script>
<script src="<?php echo $this->basePath(); ?>/templates/admin-main/assets/flot/jquery.flot.crosshair.js">
</script>
<script src="<?php echo $this->basePath(); ?>/templates/admin-main/js/jquery.peity.min.js">
</script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/templates/admin-main/assets/uniform/jquery.uniform.min.js">
</script>
<script src="<?php echo $this->basePath(); ?>/templates/admin-main/js/scripts.js">
</script>
<script>
  jQuery(document).ready(function(){
    App.setMainPage(true);
    App.init()}
                        );
</script>
</body>
</html>